export RAILS_ENV={{ medspace_rails_env }}
export RAILS_LOG_TO_STDOUT=true
export FCREPO_URL=http://127.0.0.1:8080/fcrepo/rest
export SOLR_URL=http://127.0.0.1:8983/solr/medspace
export REDIS_HOST=127.0.0.1
export SECRET_KEY_BASE="{{ medspace_secret_key_base }}"
export DEVISE_SECRET_KEY="{{ medspace_devise_secret_key }}"
export DATABASE_URL={{ medspace_database_url }}
export HANDLE_TARGET_HOSTNAME={{ medspace_handle_target_hostname }}
export HANDLE_EMAIL={{ medspace_handle_email }}
export HANDLE_PREFIX={{ medspace_handle_prefix }}
export HANDLE_ADMIN_PREFIX={{ medspace_handle_admin_prefix }}
export HANDLE_INDEX={{ medspace_handle_index }}
export HANDLE_PKEY_FILE={{ medspace_handle_pkey_file }}
export HANDLE_PKEY_PASSPHRASE=""
export HDL_HOME={{ medspace_hdl_home }}