---
version: '3.7'

services:
  web:
    build: .
    command: "bundle exec rails server -p 3000 -b '0.0.0.0' --pid /tmp/medspace.pid"
    ports:
      - 3000:3000
    env_file:
      - ./app.env
    volumes:
      - .:/srv/rails

  db:
    env_file:
     - ./app.env
    volumes:
      - mysql_data:/var/lib/mysql

  fcrepo:
    volumes:
      - fcrepo_data:/mnt/fedora-data

  solr:
    build: ./solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores

volumes:
  fcrepo_data:
  mysql_data:
  solr_data: