---

version: '3.7'

services:
  web:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    user: rails
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    command: 'bundle exec rails db:migrate'

  db:
    image: 'mariadb:10.3.0'

  redis:
    image: 'redis:3.2.9-alpine'