version: '3.7'

services:
  web:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    environment:
      FCREPO_URL: ${FCREPO_URL}
      FCREPO_BASE_PATH: /prod
      SOLR_URL: ${SOLR_URL}
      REDIS_HOST: medspace_redis_prod
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_NAMESPACE: medspace_dev
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - net
      - mariadb_net
      - medspace_fcrepo_net
      - medspace_solr_net
      - medspace_redis_net
      - traefik_net
    volumes:
      - data:/var/lib/medspace/derivatives
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.rule=Host:${CI_ENVIRONMENT_SLUG}.152.3.102.153.xip.io"

  sidekiq:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    command: 'bin/bundle exec sidekiq'
    environment:
      FCREPO_URL: ${FCREPO_URL}
      FCREPO_BASE_PATH: /prod
      SOLR_URL: ${SOLR_URL}
      REDIS_HOST: medspace_redis_prod
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_NAMESPACE: medspace_dev
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - net
      - mariadb_net
      - medspace_fcrepo_net
      - medspace_solr_net
      - medspace_redis_net
    volumes:
      - data:/var/lib/medspace/derivatives

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    networks:
      - mariadb_net
      - net
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: 'bundle exec rails db:migrate'

networks:
  net:
    driver: overlay
    driver_opts:
      encrypted: "true"
  mariadb_net:
    external: true
  medspace_fcrepo_net:
    external: true
  medspace_solr_net:
    external: true
  medspace_redis_net:
    external: true
  traefik_net:
    external: true

volumes:
  data:
    name: "medspace_${STORAGE_ENV}_data"
    driver: local
    driver_opts:
      type: nfs
      o: addr=oit-nas-fe11.oit.duke.edu,hard,rw,tcp,nfsvers=4
      device: ":/ifs/oit-nas-fe11/mcl-nas/volumes/medspace/derivatives/${STORAGE_ENV}"

