---
version: '3.7'

services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./app.env

  db:
    env_file:
     - ./app.env
    volumes:
      - mysql_data:/var/lib/mysql

  fcrepo:
    volumes:
      - fcrepo_data:/mnt/fedora-data

  solr:
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - medspace

volumes:
  fcrepo_data:
  mysql_data:
  solr_data: