version: '3.7'

services:
  web:
    image: "${APP_IMAGE}"
    command: "bin/bundle exec rails server -p 3000 -b '0.0.0.0' --pid /tmp/medspace.pid"
    environment:
      FCREPO_URL: "${FCREPO_URL}"
      FCREPO_BASE_PATH: "/prod"
      SOLR_URL: "${SOLR_URL}"
      REDIS_HOST: "medspace_redis_prod"
      REDIS_URL: "redis://medspace_redis_prod:6379"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      HANDLE_TARGET_HOSTNAME: "${HANDLE_TARGET_HOSTNAME}"
      HANDLE_EMAIL: "${HANDLE_EMAIL}"
      HANDLE_PREFIX: "${HANDLE_PREFIX}"
      HANDLE_ADMIN_PREFIX: "${HANDLE_ADMIN_PREFIX}"
      HANDLE_INDEX: "${HANDLE_INDEX}"
      HANDLE_PKEY_FILE: "${HANDLE_PKEY_FILE}"
      HANDLE_PKEY_PASSPHRASE: "${HANDLE_PKEY_PASSPHRASE}"
      HDL_HOME: "${HDL_HOME}"
      RAILS_ENV: "${ENV}"
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_NAMESPACE: "${REDIS_NAMESPACE}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    networks:
      - "net"
      - "mariadb_net"
      - "medspace_fcrepo_net"
      - "medspace_solr_net"
      - "medspace_redis_net"
      - "traefik_net"
    secrets:
      - source: "handle_admpriv"
        target: "/etc/handle/medspace/admpriv.bin"
    volumes:
      - "data:/var/lib/medspace/derivatives"
      - "/mnt/gvol0/tmp/medspace/${STORAGE_ENV}/network_files:/srv/rails/tmp/network_files"
      - "/mnt/gvol0/tmp/medspace/${STORAGE_ENV}/uploads:/srv/rails/tmp/uploads"
    deploy:
      replicas: "${REPLICAS}"
      resources:
        limits:
          memory: "2G"
      placement:
        constraints:
          - "node.labels.data != true"
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.rule=Host:${HOST_NAME}"

  sidekiq:
    image: "${APP_IMAGE}"
    command: "bin/bundle exec sidekiq"
    environment:
      FCREPO_URL: "${FCREPO_URL}"
      FCREPO_BASE_PATH: "/prod"
      SOLR_URL: "${SOLR_URL}"
      REDIS_HOST: "medspace_redis_prod"
      REDIS_URL: "redis://medspace_redis_prod:6379"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      HANDLE_TARGET_HOSTNAME: "${HANDLE_TARGET_HOSTNAME}"
      HANDLE_EMAIL: "${HANDLE_EMAIL}"
      HANDLE_PREFIX: "${HANDLE_PREFIX}"
      HANDLE_ADMIN_PREFIX: "${HANDLE_ADMIN_PREFIX}"
      HANDLE_INDEX: "${HANDLE_INDEX}"
      HANDLE_PKEY_FILE: "${HANDLE_PKEY_FILE}"
      HANDLE_PKEY_PASSPHRASE: "${HANDLE_PKEY_PASSPHRASE}"
      HDL_HOME: "${HDL_HOME}"
      RAILS_ENV: "${ENV}"
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_NAMESPACE: "${REDIS_NAMESPACE}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    healthcheck:
      disable: true
    networks:
      - "net"
      - "mariadb_net"
      - "medspace_fcrepo_net"
      - "medspace_solr_net"
      - "medspace_redis_net"
    secrets:
      - source: "handle_admpriv"
        target: "/etc/handle/medspace/admpriv.bin"
    volumes:
      - "data:/var/lib/medspace/derivatives"
      - "/mnt/gvol0/tmp/medspace/${STORAGE_ENV}/network_files:/srv/rails/tmp/network_files"
      - "/mnt/gvol0/tmp/medspace/${STORAGE_ENV}/uploads:/srv/rails/tmp/uploads"
    deploy:
      resources:
        limits:
          memory: "2G"
      placement:
        constraints:
          - "node.labels.data != true"

  db_migrate:
    image: "${APP_IMAGE}"
    restart: 'on-failure'
    networks:
      - mariadb_net
      - net
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: 'bin/rails db:migrate'

networks:
  net:
    driver: overlay
    driver_opts:
      encrypted: "true"
  mariadb_net:
    external: true
  medspace_fcrepo_net:
    external: true
  medspace_solr_net:
    external: true
  medspace_redis_net:
    external: true
  traefik_net:
    external: true

secrets:
  handle_admpriv:
    external: true

volumes:
  data:
    name: "medspace_${STORAGE_ENV}_data"
    driver: local
    driver_opts:
      type: nfs
      o: addr=oit-nas-fe11.oit.duke.edu,hard,rw,tcp,nfsvers=4
      device: ":/ifs/oit-nas-fe11/mcl-nas/volumes/medspace/derivatives/${STORAGE_ENV}"