---
version: '3.7'

services:
  prod:
    image: 'redis:3.2.9-alpine'
    command: "redis-server --appendonly yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "30s"
      timeout: "10s"
      retries: 3
    networks:
      - net
    volumes:
      - data:/data

networks:
  net:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=oit-nas-fe11.oit.duke.edu,hard,rw,tcp,nfsvers=4
      device: ":/ifs/oit-nas-fe11/mcl-nas/volumes/medspace/redis"
