---
version: '3.7'

services:
  web:
    build: .
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    user: rails
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    env_file:
      - ./app.env

  db:
    image: 'mariadb:10.3.0'
    env_file:
     - ./app.env
    volumes:
      - mysql_data:/var/lib/mysql

  fcrepo:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace/fcrepo'
    volumes:
      - fcrepo_data:/mnt/fedora-data

  redis:
    image: 'redis:3.2.9-alpine'

  solr:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace/solr'
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - medspace

volumes:
  fcrepo_data:
  mysql_data:
  solr_data: