version: '3.7'

services:
  web:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    environment:
      FCREPO_URL: ${FCREPO_URL}
      SOLR_URL: ${SOLR_URL}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
    networks:
      - net
      - medspace_fcrepo_net
      - medspace_solr_net
      - traefik_net
    volumes:
      - data:/var/lib/medspace/derivatives
    env_file:
      - ./app.env
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.rule=Host:${CI_ENVIRONMENT_SLUG}.152.3.102.153.xip.io"

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    networks:
      - net
    env_file:
      - ./app.env
    command: 'bundle exec rails db:migrate'

  db:
    image: 'mariadb:10.3.0'
    networks:
      - net
    env_file:
      - ./app.env

  redis:
    image: 'redis:3.2.9-alpine'
    networks:
      - net

networks:
  net:
    driver: overlay
    driver_opts:
      encrypted: "true"
  medspace_fcrepo_net:
    external: true
  medspace_solr_net:
    external: true
  traefik_net:
    external: true

volumes:
  data:
    name: "medspace_${STORAGE_ENV}_data"
    driver: local
    driver_opts:
      type: nfs
      o: addr=oit-nas-fe11.oit.duke.edu,hard,rw,tcp,nfsvers=4
      device: ":/ifs/oit-nas-fe11/mcl-nas/volumes/medspace/derivatives/${STORAGE_ENV}"

