---
version: '3.7'

services:
  web:
    build: .
    command: "bundle exec rails server -p 3000 -b '0.0.0.0' --pid /tmp/medspace.pid"
    ports:
      - 3000:3000
    env_file:
      - ./app.env
    volumes:
      - .:/srv/rails
      - ./snapshot/derivatives:/srv/rails/tmp/derivatives

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    env_file:
      - ./app.env
    command: 'bundle exec rails db:migrate'

  db:
    image: mariadb
    env_file:
     - ./app.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./snapshot/mariadb:/docker-entrypoint-initdb.d

  fcrepo:
    build: ./docker-fcrepo
    volumes:
      - fcrepo_data:/mnt/fedora-data
      - ./snapshot/fcrepo:/docker-entrypoint-init.d
    ports:
      - 8080:8080

  solr:
    build: ./solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./snapshot/solr:/docker-entrypoint-init.d
      - ./solr:/config
    ports:
      - 8983:8983

volumes:
  fcrepo_data:
  mysql_data:
  solr_data: