version: '2'

services:
  web:
    image: 'dumclibrary/medspace'
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    env_file:
      - ./app.env
    ports:
      - 127.0.0.1:3000:3000

  db_migrate:
    image: 'dumclibrary/medspace'
    restart: 'on-failure'
    env_file:
          - ./app.env
    command: 'bundle exec rails db:migrate'

  fcrepo:
    image: 'dumclibrary/fcrepo'

  redis:
    image: 'redis:3.2.9-alpine'

  solr:
    image: 'solr:6.6.0-alpine'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - medspace
      - /config
    volumes:
      - ./solr/config:/config