---

version: '3.7'

services:
  web:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    user: rails
    command: supervisord

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    command: 'bundle exec rails db:migrate'