---

version: '3.7'

services:
  web:
    build: .
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    user: rails
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    env_file:
      - ./app.env