version: '3.7'

services:
  web:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    environment:
      FCREPO_URL: ${FCREPO_URL}
      SOLR_URL: ${SOLR_URL}
    networks:
      - net
      - medspace_fcrepo_net
      - medspace_solr_net
      - traefik_net
    env_file:
      - ./app.env
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.rule=Host:${CI_ENVIRONMENT_SLUG}.152.3.102.153.xip.io"

  db_migrate:
    image: 'gitlab-registry.oit.duke.edu/mclibrary/medspace'
    restart: 'on-failure'
    networks:
      - net
    env_file:
      - ./app.env
    command: 'bundle exec rails db:migrate'

  db:
    image: 'mariadb:10.3.0'
    networks:
      - net
    env_file:
      - ./app.env

  redis:
    image: 'redis:3.2.9-alpine'
    networks:
      - net

networks:
  net:
    driver: overlay
    driver_opts:
      encrypted: "true"
  medspace_fcrepo_net:
    external: true
  medspace_solr_net:
    external: true
  traefik_net:
    external: true
