---
# Hack to get synchronize module working locally for testing
medspace_host: ""

medspace_ruby_environment:
  PATH: /opt/rh/rh-ruby23/root/usr/local/bin:/opt/rh/rh-ruby23/root/usr/bin:/opt/rh/rh-git29/root/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ffmpeg
  LD_LIBRARY_PATH: /opt/rh/rh-ruby23/root/usr/local/lib64:/opt/rh/rh-ruby23/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64
  MANPATH: /opt/rh/rh-ruby23/root/usr/local/share/man:/opt/rh/rh-ruby23/root/usr/share/man:/opt/rh/rh-git29/root/usr/share/man
  PKG_CONFIG_PATH: /opt/rh/rh-ruby23/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby23/root/usr/lib64/pkgconfig
  XDG_DATA_DIRS: /opt/rh/rh-ruby23/root/usr/local/share:/opt/rh/rh-ruby23/root/usr/share