terms:
  - id: Duke Medical Center Archives
    term: Duke Medical Center Archives
  - id: David M. Rubenstein Rare Book & Manuscript Library
    term: David M. Rubenstein Rare Book & Manuscript Library
  - id: Duke Medical Center Library & Archives
    term: Duke Medical Center Library & Archives
  - id: PA History Center
    term: PA History Center
