terms:
  - id: Advancing Inclusion, Diversity, Equity, and Accessibility in Libraries and Archives (IDEAL) Conference
    term: Advancing Inclusion, Diversity, Equity, and Accessibility in Libraries and Archives (IDEAL) Conference
  - id: Association of American Medical Colleges (AAMC) Learn Serve Lead
    term: Association of American Medical Colleges (AAMC) Learn Serve Lead
  - id: Association of College and Research Libraries (ACRL)
    term: Association of College and Research Libraries (ACRL)
  - id: Association of North Carolina Health and Science Libraries (ANCHASL)
    term: Association of North Carolina Health and Science Libraries (ANCHASL)
  - id: Charleston Conference, Charleston, SC
    term: Charleston Conference, Charleston, SC
  - id: Duke AHEAD Education Day
    term: Duke AHEAD Education Day
  - id: Duke/UNC Joint Health Informatics Seminar
    term: Duke/UNC Joint Health Informatics Seminar
  - id: Evidence-Based Librarianship Conference
    term: Evidence-Based Librarianship Conference
  - id: Medical Library Association (MLA)
    term: Medical Library Association (MLA)
  - id: MLA/Mid-Atlantic Chapter (MAC)
    term: MLA/Mid-Atlantic Chapter (MAC)
  - id: North Carolina Preservation Consortium (NCPC)
    term: North Carolina Preservation Consortium (NCPC)
  - id: Physician Assistant Education Association (PAEA) Education Forum
    term: Physician Assistant Education Association (PAEA) Education Forum
  - id: Society of American Archivists (SAA)
    term: Society of American Archivists (SAA)
  - id: Society of North Carolina Archivists (SNCA)
    term: Society of North Carolina Archivists (SNCA)
  - id: Southern Chapter of the Medical Library Association (SC/MLA)
    term: Southern Chapter of the Medical Library Association (SC/MLA)
  - id: Transformational Change in Health Sciences Libraries Conference
    term: Transformational Change in Health Sciences Libraries Conference
  - id: Triangle Research Library Network Annual Meeting (TRLN)
    term: Triangle Research Library Network Annual Meeting (TRLN)