terms:
  - id: Association of North Carolina Health and Science Libraries (ANCHASL)
    term: Association of North Carolina Health and Science Libraries (ANCHASL)
  - id: Charleston Conference, Charleston, SC
    term: Charleston Conference, Charleston, SC
  - id: Duke/UNC Joint Health Informatics Seminar
    term: Duke/UNC Joint Health Informatics Seminar
  - id: Evidence-Based Librarianship Conference
    term: Evidence-Based Librarianship Conference
  - id: Medical Library Association (MLA)
    term: Medical Library Association (MLA)
  - id: MLA/Mid-Atlantic Chapter (MAC)
    term: MLA/Mid-Atlantic Chapter (MAC)
  - id: Transformational Change in Health Sciences Libraries Conference
    term: Transformational Change in Health Sciences Libraries Conference
