---
- name: create medspace system user
  user:
    name: "{{ medspace_user }}"
    system: yes

- name: copy files to server
  synchronize:
    src: ../../../..
    dest: "{{ medspace_host_synchronize_hack }}/srv/"
    delete: yes
    checksum: yes
    archive: no
    links: yes
    owner: no
    group: no
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.idea"
      - "--exclude=ansible"
      - "--exclude=public/assets"
      - "--exclude=log/*"
      - "--exclude=solr"
      - "--exclude=docker-fcrepo"
      - "--exclude=db/*"
  become_user: "{{ medspace_user }}"

- name: set correct ownership
  file:
    path: /srv/medspace
    owner: "{{ medspace_user }}"
    group: "{{ medspace_user }}"
    recurse: yes

- name: install bundle
  gem:
    name: bundler
    state: present
  environment: "{{ medspace_environment }}"
  become_user: "{{ medspace_user }}"

- name: install gems
  bundler:
    chdir: /srv/medspace
    state: present
    executable: /srv/medspace/bin/bundle
  environment: "{{ medspace_environment }}"
  become_user: "{{ medspace_user }}"

- name: perform database migration
  shell: bin/rails db:migrate RAILS_ENV=production
  args:
    chdir: /srv/medspace
  environment: "{{ medspace_environment }}"
  become_user: "{{ medspace_user }}"

- name: compile assets
  shell: bin/rails assets:precompile RAILS_ENV=production
  args:
    chdir: /srv/medspace
    creates: /srv/medspace/public/assets
  environment: "{{ medspace_environment }}"
  become_user: "{{ medspace_user }}"

- name: copy medspace environment file
  template:
    src: medspace.env
    dest: /etc/default/medspace.env

- name: copy medspace services
  template:
    src: "{{ item }}.service"
    dest: /etc/systemd/system/
  with_items: "{{ medspace_services }}"
  register: medspace_services_task
  notify:
    - restart medspace services

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: medspace_services_task.changed

- name: enable medspace services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ medspace_services }}"